version: '1.1'
services:
  mysql:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=auth
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=123
    volumes:
      - ./mysql:/var/lib/mysql
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
        - DB_URL=mysql:3306
    depends_on:
      - mysql
    command: [ "/wait-for-it.sh", "mysql:3306", "-t", "180", "--", "/entrypoint.sh" ]
    #use  'docker-compose run -p8082:8082 auth' to run the container
